packages:
  - "apps/*"
  - "packages/*"
  - "test/*"

managePackageManagerVersions: false
strictDepBuilds: false

onlyBuiltDependencies:
  - esbuild

ignoredBuiltDependencies:
  - msw
  - sharp
  - unrs-resolver
